name: SkylliaExtra
version: ${version}
main: fr.euphyllia.skylliaextra.SkylliaExtra
api-version: 1.20.6
folia-supported: true
authors:
  - Euphyllia

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
