name: SkylliaBackup
version: ${version}
main: fr.euphyllia.skylliabackup.SkylliaBackup
api-version: 1.20.6
folia-supported: true
description: "Island backup addon for Skyllia — creates .mca ZIPs and optionally uploads them."

dependencies:
  server:
    Skyllia:
      load: BEFORE
      required: true
      join-classpath: true
